### ISSUE TITLE
Use babel-library-boilerplate

### ISSUE THREAD

**Issue by paulfalgout** [benmccormick/marionette-service#1]
https://github.com/babel/babel-library-boilerplate

**Comment by benmccormick** [comment]
Considered this (or @jmeas's version actually), but there's actually no reason at all to use ES6 for this library.  Babel only produced some overhead code that wasn't needed.  I love ES6, but there wasn't a single way that it made this code base better.  So I'd rather keep it simple.

**Comment by benmccormick** [comment]
This has been added and then simplified down.  We're not using Babel, and we're not using many of the bells and whistles of the boilerplate, but it provided a nice jump start on setting up tests, so :+1:
