### ISSUE TITLE
Don't attach Service to the Mn object

### ISSUE THREAD

**Issue by paulovieira** [benmccormick/marionette-service#11]
The `Service` object is always attached to the `Mn` object, even when using CJS modules. This happens at the end of the code:

``` js
Mn.Service = Service;
```

This is unexpected because I want to use the "Service" property for other stuff, but when I require marionette-service, it will override it.

A better approach would be to attach to Mn only if the user is not using any module system. This is what is done in marionette.state, for instance:

https://github.com/Squareknot/marionette.state

**Comment by benmccormick** [comment]
Hmm, I hear you on this.  I do prefer modules to namespacing.  At the same time, I don't like changing the behavior based on how the file is loaded.  That feels inconsistent to me.  And seems like it would be solving this problem for the people who don't really need it.  The folks who aren't using modules would seem to be the most likely to be using Mn as a namespace and risking naming conflicts.  

May I ask what it is that you're doing that leads to a naming collision?

**Comment by benmccormick** [comment]
I think this is pretty standard for Backbone libs at least, and follows the conventions of Bb/Mn themselves

BB.Validation: https://github.com/thedersen/backbone.validation/blob/master/dist/backbone-validation-amd.js
BB.Radio: https://github.com/marionettejs/backbone.radio/blob/master/build/backbone.radio.js

Backbone.stickit: https://github.com/NYTimes/backbone.stickit/blob/master/backbone.stickit.js

Backbone.Relational: https://github.com/PaulUithol/Backbone-relational/blob/master/backbone-relational.js#L64

**Comment by paulovieira** [comment]
Yes, there are pros and cons. It's not that important though. I feel it is more a matter of principle: when a module is required, it shouldn't "invade" the space of other modules. If I want to attach it to other module, I should do it explicitely.

Thanks for thinking about it.
