### ISSUE TITLE
Add tests and test across multiple environments

### ISSUE THREAD

**Issue by paulfalgout** [benmccormick/marionette-service#2]
https://github.com/RoundingWellOS/marionette.toolkit/pull/114/files#diff-354f30a63fb0907d4ad57269548329e3R4

**Comment by benmccormick** [comment]
I'd like to do this but haven't had the time yet.  Right now the code is pulled directly out of the Marionette major branch, where it is tested.  I intend to track that code unless a huge change is made that I don't agree with.  

That said, independent tests are a good idea and I would love a pull request.  Feel free to start with the tests I've already written in the Marionette repo.  If you add any extra tests it would be lovely if you PRed them back into Mn as well.

**Comment by benmccormick** [comment]
This is done
